// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Account struct {
	ID        int64        `json:"id"`
	Owner     string       `json:"owner"`
	Balence   int64        `json:"balence"`
	Currency  string       `json:"currency"`
	CreatedAt sql.NullTime `json:"createdAt"`
}

type Entry struct {
	ID        int64        `json:"id"`
	AccountID int64        `json:"account_id"`
	Amount    int64        `json:"amount"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Transfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	// positive only
	Amount    int64        `json:"amount"`
	CreatedAt sql.NullTime `json:"created_at"`
}
